# Generated by Django 3.1.3 on 2020-12-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS351_Project', '0003_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='username',
        ),
    ]
