# Generated by Django 3.1.3 on 2020-12-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS351_Project', '0005_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
